### ISSUE TITLE
Import from Evernote

### ISSUE THREAD

**Issue by chuckg** [inkdropapp/forum#10]
For those of us converting from Evernote it would be fantastic if there was a basic import from Evernote to Inkdrop. The reverse is not necessary.

**Comment by craftzdog** [comment]
Thank you for your suggestion.
I don't plan to support that in this beta phase because our server is not ready yet to treat many notes potentially added at once via Evernote. More stability tests for that are needed.

**Comment by livejamie** [comment]
Is this still the case?

**Comment by craftzdog** [comment]
Yep, it's in the roadmap: https://medium.com/@inkdrop/the-future-work-of-inkdrop-8c50c4e06e6c

**Comment by craftzdog** [comment]
Supported in v3.9.0.
Check out this blogpost: https://blog.inkdrop.info/how-to-migrate-your-notes-from-evernote-to-inkdrop-2f0559616ed5
Thanks again!
