### ISSUE TITLE
Link to a note from within a note.

### ISSUE THREAD

**Issue by platypython** [inkdropapp/forum#11]
Perhaps if a note called 'bash tricks' existed, you could reference it in another note with [bash tricks] or [[bash tricks]]

**Comment by craftzdog** [comment]
That's a great idea!
Planning to support in the future.

**Comment by craftzdog** [comment]
It's supported in v0.5.0.
https://medium.com/@inkdrop/inkdrop-v0-5-0-release-notes-2b359f6c7bd8
