### ISSUE TITLE
Malfunction of a note screen and the preview screen.

### ISSUE THREAD

**Issue by hokuto-kato** [inkdropapp/forum#12]
# 不具合
- 特定の記事のプレビュー画面で幅が変わる
- スクロール中に突然幅が変わる
- 改行されなくなる

動画をとってみたのでご確認ください。
https://drive.google.com/file/d/0B8Cuc9e0dgWGYlZvSVh0U1VhOG8/view

１行で長いソースのシンタックスがあると起きるのかも・・・？
# 再現環境
## OS

OSX 10.11.5
## InkDrop

0.6.0 

念のため、該当のmdファイルを添付しておきます。
[xpath.md.zip](https://github.com/inkdropapp/forum/files/356087/xpath.md.zip)

---
# Malfunction
- Width changes with the preview screen of the specific article
- Width changes during scroll suddenly
- It is not started a new line
  I took an movie, please identify .
  https://drive.google.com/file/d/0B8Cuc9e0dgWGYlZvSVh0U1VhOG8/view
# Reproduction environment
## OS

OSX 10.11.5
## InkDrop

0.6.0 

I attach applicable md file just to make sure.
[xpath.md.zip](https://github.com/inkdropapp/forum/files/356087/xpath.md.zip)

**Comment by craftzdog** [comment]
ご報告ありがとうございます！
こちらはSide-by-Sideモードの時のみに発生するようですね。
調査してみます。

It seems that the problem occurs only on side-by-side mode.
I'll look into it. Thanks.

**Comment by craftzdog** [comment]
Resolved in v0.6.2.
Thanks again!
