### ISSUE TITLE
bug when I make a new note.

### ISSUE THREAD

**Issue by hokuto-kato** [inkdropapp/forum#13]
# 不具合

新しいノートを作成した時に、その時に選択しているノートの内容を引き継いでしまいます。
## OS

OSX 10.10.5
## Inkdrop

 0.6.0
## 動画

https://drive.google.com/file/d/0B8Cuc9e0dgWGY2Fja3RZaEwwV1k/view

---
# bug

When I made a new note, the contents of the note which I choose are copied.
## OS

OSX 10.10.5
## Inkdrop

 0.6.0
## movie

https://drive.google.com/file/d/0B8Cuc9e0dgWGY2Fja3RZaEwwV1k/view

**Comment by craftzdog** [comment]
ご報告ありがとうございます！
これは致命的なバグですね。
すぐに修正版を公開します。

Seems to be a critical bug.
I'm fixing it right now.
Thanks for your patience.

**Comment by craftzdog** [comment]
resolved in v0.6.1.
Thanks!
