### ISSUE TITLE
Note/Notebook sharing and publishing 

### ISSUE THREAD

**Issue by koliyo** [inkdropapp/forum#14]
I want to be able to share individual notes and notebooks with other people.
I would also like to be able to do this with people that does not have inkdrop, some sort of publish feature to a web page where the notes can be read.

I guess you are planning to expose some functionality natively in the browser since the app is built with web technologies?

**Comment by craftzdog** [comment]
Thanks for the feature request!
Sharing and publishing features are exactly useful.
I'm currently focusing to develop Inkdrop's core features so those features will be considered in the future.
In addition, Inkdrop exposes data access API. I'm going to write documentation about it soon.
Using this API, you can make something that enables to share your notes individually to people who doesn't have Inkdrop.

**Comment by craftzdog** [comment]
Supported as of v3.8.0.
Learn more: https://community.inkdrop.info/note/d975606d93c067c5ef8d6adfb5db83b5/note:ry4uCPHuZ
Thanks for the suggestion!
