### ISSUE TITLE
Allow storing passwords in keychain

### ISSUE THREAD

**Issue by lucascaro** [inkdropapp/forum#15]
It would be awesome to be able to store encryption passwords in my osx keychain, so that I don't need to remember / copy&paste.

**Comment by craftzdog** [comment]
Thanks for the request!
Storing encryption passwords in keychain is a feature nice to have.
But not now, it'll be considered in the future.

**Comment by craftzdog** [comment]
Data at rest encryption is now supported and the note encryption with password is deprecated.
You no longer need a password to encrypt notes.
Read a blog post for detail info: https://medium.com/@inkdrop/inkdrop-v0-11-0-is-out-b708a9c2cd49
