### ISSUE TITLE
"Update Now" button in the dialogue hides when Inkdrop was upgraded.

### ISSUE THREAD

**Issue by hokuto-kato** [inkdropapp/forum#16]
"Update Now" button in the dialogue hides when InkDrop was upgraded.
![image](https://cloud.githubusercontent.com/assets/10446161/18335833/67c9e398-75bd-11e6-87bf-c37e8baf748a.png)
Inkdropがアップグレードされた際に表示される「Update Now」ボタンが隠れてしまっていて押せません。（タブを押せばたどり着けます）

**Comment by craftzdog** [comment]
Ooops! It appears the stylesheet is not applied well.
Thanks for the report!

**Comment by craftzdog** [comment]
Resolved in v1.0.0

**Comment by hokuto-kato** [comment]
Mmm, ... not resolved.
Possibly it may be to be my environmental result.
![2016-10-03 15 26 21](https://cloud.githubusercontent.com/assets/10446161/19031059/dfd8a6f2-898c-11e6-90bd-6fd4dc6a45e8.png)

うーん、直ってないような・・・。
もしかしたら、こちらの環境のせいなのかもしれませんね。

**Comment by craftzdog** [comment]
Yes, it's fixed in the latest version.
You should see correct update window from v1.0.0.

最新版からアップデートウインドウが正しく表示されます。
現在ご覧になっているのは修正前のバージョンによる表示です。

**Comment by hokuto-kato** [comment]
そうか！　そうですよね・・・😅
失礼いたしました！
