### ISSUE TITLE
Support iCloud and/or Dropbox

### ISSUE THREAD

**Issue by nicoschuele** [inkdropapp/forum#17]
Inkdrop looks like a beautiful app that would likely solve my issue of keeping technical notes at hands. Unfortunately, I don't feel really good using a (yet) unknown sync service. **a)** I'm not really trusting the security and **b)** too many are going down if the product doesn't gain traction. If my data were stored in iCloud or Dropbox, I'd use it immediately.

**Comment by craftzdog** [comment]
Unfortunately, no.
But Inkdrop is compatible with CouchDB so you can deploy it by yourself and store your notes in it.
See the [documentation](http://doc.inkdrop.info/manual/synchronizing-in-the-cloud#how-to-set-up-your-own-sync-server).
