### ISSUE TITLE
UI shows empty squares in the place of icons

### ISSUE THREAD

**Issue by jmcmichael** [inkdropapp/forum#18]
After I first opened the app (v1.0.0 beta), the UI looked like the attached screenshot.

![screen shot 2016-10-03 at 9 11 49 am](https://cloud.githubusercontent.com/assets/132909/19040454/b9eebdfc-8949-11e6-8feb-416012838385.png)

Based on screenshots on the site, those should be icons. I have an app called Font Explorer Pro that I use to manage fonts and am switching around fonts sets quite often, and run across these issues in some apps from time to time.

**Comment by craftzdog** [comment]
I can't fix the problem caused by other app.
Please report it to the Font Explorer Pro support.

**Comment by jmcmichael** [comment]
My issue wasn't 'Inkdrop shows blank squares when used with FontExplorer Pro'. I believe that this issue is a sign that Inkdrop has a problem working with font management applications in general.

The same problem would (likely) occur with Font Book, Apple's built-in management application which does the same thing as FontExporer, but with fewer features.

I expect that you will have more potential users reporting this problem in the future. I use a wide variety of applications and none of them exhibit this behavior. I'm happy to work with you on solving this problem by providing you with logging details and troubleshooting help, if you wish to address this issue in the future.

**Comment by craftzdog** [comment]
Icons are web font and not system font.
The blank squares potentially appear if the app failed to load the web font, and you should see an error in the console of the developer tool.
You can open the console from `Developer -> Toggle Developer Tools` from menu.
Please tell me if you got the error.

If the font loaded successfully but the squares appeared, there may be nothing I can do.
[Electron](https://github.com/electron/electron), the app is built with, may be responsible for this problem.

**Comment by craftzdog** [comment]
Have you installed a font named 'Icons'?
It's possible that the local font replaces the web font when they are same name.
