### ISSUE TITLE
Ctrl-k to insert hyperlink 

### ISSUE THREAD

**Issue by kjaymiller** [inkdropapp/forum#19]
There are already hot keys for bold and italics that translate to markdown but there is no hyperlink hotkey. 

Can ctrl+k and CMD+k be used to insert `[highlighted text]()`?

**Comment by craftzdog** [comment]
`Shift+Cmd+A` is current hot key for inserting a hyperlink.
It seems to be a bug that a tooltips of the 'Create Link' button on the toolbar represents 'Cmd+K' but it's incorrect.
Thanks your reporting!

**Comment by kjaymiller** [comment]
So should it be shift+CMD+a or CMD+k?

Sent usingZero App(https://itunes.apple.com/app/apple-store/id972932698?pt=117141995&ct=sentwithzero&mt=8)

**Comment by craftzdog** [comment]
`Shift+Cmd+a` is a default keybinding for inserting a link.
You can also customize it from preferences.
![screen shot 2016-10-08 at 8 21 02](https://cloud.githubusercontent.com/assets/1332805/19208000/4a36b63c-8d30-11e6-8ed8-ef5d4128a83d.png)

**Comment by kjaymiller** [comment]
That works for me!! Thank you. 🔍

**Comment by craftzdog** [comment]
Good to hear that :)

**Comment by craftzdog** [comment]
Fixed in v2.0.0
