### ISSUE TITLE
Sync spinner is distracting

### ISSUE THREAD

**Issue by josefdlange** [inkdropapp/forum#2]
Even with Inkdrop in the background, the bottom-left sync state spinner and info is a little distracting when it's spinning. I'd suggest either toning down the color or making the spinner itself smaller. Or both.

**Comment by craftzdog** [comment]
Good point. Seems rotating speed of the spinner is also too fast and should be slowed down.
Thanks for your suggestion!

**Comment by CodeKiwi** [comment]
+1 I resorted to moving the window slightly off screen so as to not be distracted. I think just a last sync'd date would be sufficient. As a user I don't think I need to know when its syncing.

**Comment by craftzdog** [comment]
@CodeKiwi yeah, the spinner will be gone in the next version. thanks for your suggestion!

**Comment by craftzdog** [comment]
resolved in v0.3.0
