### ISSUE TITLE
Clicking near the top of bottom of text editing window automatically scrolls

### ISSUE THREAD

**Issue by ironmike-au** [inkdropapp/forum#21]
If I have a note that is longer than one page, clicking on text on the top or bottom 4 or 5 lines will automatically scroll the text up or down. I don't think this should happen and isn't behaviour I have seen in other apps. 

For example, in this image I can click on the 'dayofmonth' text that appears on line 19. Note that line 22 is the last line in my view.  
![image](https://cloud.githubusercontent.com/assets/9390978/20783331/ea7d1a0e-b7de-11e6-97c8-8ca9ede9e0e6.png)

After clicking, the text is automatically scrolled down and now the last line is 24. 
![image](https://cloud.githubusercontent.com/assets/9390978/20783380/3f1a8e66-b7df-11e6-9127-0150b9c88d5a.png)

This behaviour also occurs if you click+hold, as if you wanted to highlight the word 'dayofmonth'. In this case, the scroll still happens and if you try to drag your mouse it will scroll wildly (generally seems to do a vertical selection, rather than a horizontal selection. 

Is it possible to change the default behaviour so that auto-scrolling on mouse click doesn't happen anywhere?

Thanks!

**Comment by craftzdog** [comment]
This is due to 'Cursor Scroll Margin'.
You can set it to `0` from 'Editing' preferences to disable auto-scrolling when clicking on the edge.
Hope it helps!

**Comment by ironmike-au** [comment]
That's great - thanks!
