### ISSUE TITLE
Disabling the shortcut Ctrl+F assigned to "find in the current note"

### ISSUE THREAD

**Issue by ymatz** [inkdropapp/forum#23]
`Ctrl+F` is used as a shortcut for "find in the current note" feature, but I want to disable it (and perhaps assign another shortcut to the feature) because I use `Ctrl+F` for moving cursor forward. Is it possible?

**Comment by craftzdog** [comment]
Good suggestion!
It's currently not possible to change the keymaps for 'find in the current note' and other editor shortcuts because they're hard-coded for now.
I'd support vim & emacs keymaps in the future version.
So it's planned to be configurable.

**Comment by craftzdog** [comment]
Supported in v2.6.0.
You can now customize editor keymaps like so:
![screen shot 2016-12-07 at 15 11 51](https://cloud.githubusercontent.com/assets/1332805/20956822/acb245cc-bc8f-11e6-997f-469f9c9f5ba2.png)

 * Go to the Keybindings on Preferences
 * Open user keymap file
 * Add your keymap like this:

```
'.CodeMirror':
  'ctrl-f': 'editor:go-char-left'
```

You can find available commands for editor by searching keybindings with `editor:` on the Preferences pane.

Closing it.
