### ISSUE TITLE
Mark CheckBoxes as Complete in HTML View

### ISSUE THREAD

**Issue by kjaymiller** [inkdropapp/forum#24]
You can see empty checkboxes ([] in markdown) and completed boxes ([x]), but you can't complete the checkbox in the html view.

**Comment by craftzdog** [comment]
Yes, it needs some hacks to bind Markdown code with corresponding checkbox.

**Comment by craftzdog** [comment]
It's supported in v3.4.0! Thanks for the suggestion.
