### ISSUE TITLE
app freezes - new install

### ISSUE THREAD

**Issue by riotejas** [inkdropapp/forum#26]
downloaded app and created account today.  After about 5 to 10 new notes the app hangs.  I wait a few mins and have to force quit.  I also changed to local store to see if it was hanging trying to contact cloud storage, still hangs. Also when I restart several of my latest notes are now missing.  I've duplicated this 6 times throughout the day.

I had previously downloaded the demo and played with it for awhile.  Deleted the demo app and then downloaded and installed the full version.

Version 2.7.0 (2.7.0)
macOS Sierra Version 10.12.1 (16B2555)

**Comment by craftzdog** [comment]
It's weird. Seems like there is an infinity loop in the rendering process. I'll look into it.
Thank you for your report!

**Comment by riotejas** [comment]
The only other info that might be helpful is for each new note I was manually copy/pasting from Quiver.  So i was adding a note about every 10 secs.

**Comment by craftzdog** [comment]
Got it!
I found a bug where reloading note list occurring with a few notes.
Update will be soon available. Thanks!

**Comment by craftzdog** [comment]
v2.7.1 is out.
@riotejas Could you try again with this version?
https://www.inkdrop.info/download

**Comment by riotejas** [comment]
v2.7.1 fixed
I added 200 new notes without issue
Thanks for the *quick* turnaround!

**Comment by craftzdog** [comment]
Cheers🎉
