### ISSUE TITLE
Be able to copy URLs on links using "view" mode

### ISSUE THREAD

**Issue by vianneychacon** [inkdropapp/forum#28]
When using the view mode, if you _right click_ on a link it'll be nice to be able to copy the link URL instead of the title (or at least have the option), is useless to copy the link title if you're using a title differing from the real URL.

**Comment by craftzdog** [comment]
Yeah, it's nice to have a context menu for copying URL in the markdown preview.
Thanks for your feature request!

**Comment by craftzdog** [comment]
Supported in v3.5.0. Thanks!
