### ISSUE TITLE
Unexpected characters on the preferences window

### ISSUE THREAD

**Issue by Kwadz** [inkdropapp/forum#29]
![inkdrop-bug](https://cloud.githubusercontent.com/assets/1472599/21390440/4f6890e4-c787-11e6-8f93-22f3d301fb7d.jpg)

**Comment by craftzdog** [comment]
Hi, thank you for your report.
Could you tell me more information for the investigation?

 * Please check if you got any error in the console log by selecting the menu: `Developer -> Toggle Developer Tools`.
* App Version
* Steps to reproduce (if possible)

Does it still occur after restarting the app?

**Comment by Kwadz** [comment]
Nothing in the console.
Inkdrop version 3.0.0
To reproduce: go to preferences

The problem disappeared after restarting.
