### ISSUE TITLE
Unable to install the math plugin

### ISSUE THREAD

**Issue by ymatz** [inkdropapp/forum#30]
I tried to install the math plugin and got the error message: "No available version compatible with the installed Inkdrop version: 3.1.1". Would be happy if the plugin is updated!

### Info
- Platform: macOS
- Platform version: Sierra
- App Version: 3.1.1

**Comment by craftzdog** [comment]
Oops. Sure, please wait for a while.
Thanks for your report!

**Comment by craftzdog** [comment]
All plugins now support `inkdrop@^3.1.1`. Thanks again.

**Comment by ymatz** [comment]
Now the installation worked successfully. Thanks!
