### ISSUE TITLE
Cannot search notes in Korean

### ISSUE THREAD

**Issue by jihunx** [inkdropapp/forum#31]
## Bug report
It cannot search notes in Korean. English works well.

### Info
- Platform: Windows
- Platform version: 10
- App Version: 3.1.2

### Reproduce
Write the steps for others to reproduce issue here.
![image](https://cloud.githubusercontent.com/assets/25073589/22421721/ea101e14-e72b-11e6-912e-f5d657b94927.png)

**Comment by craftzdog** [comment]
Sorry, Korean is not supported because the app uses 'lunr' as the search engine and it doesn't support Korean yet:
https://github.com/MihaiValentin/lunr-languages
Your contribution will be appreciated!
