### ISSUE TITLE
Difficult to copy/paste into Inkdrop iOS

### ISSUE THREAD

**Issue by jhartST** [inkdropapp/forum#33]
## Bug report

I seem to be unable to copy and paste easily within Inkdrop, or paste from other sources, which is one of my primary uses cases on mobile.

### Info
- Platform: iOS
- Platform version: 10.2.1
- App Version: 1.1.0 (4)

### Reproduce
Attempt to call up *copy/paste* options by clicking near cursor in Edit mode, or highlight text within Editor or View. The iOS Cut/Copy/Paste/Replace/etc. commands seldom display immediately/as expected. I can typically get them to appear after a few clicks.

**Comment by craftzdog** [comment]
Hi!

Thanks for your report.
I guess the editor is preventing default tap behavior. I'll look into it!

**Comment by craftzdog** [comment]
Just published v1.1.0 (11) on TestFlight which attempts to fix this problem.
I'd like to know if it doesn't cause a side effect.
Can you try it?

**Comment by jhartST** [comment]
The bug looks to be resolved in v1.1.0 (11). I'll do some smoke testing today to see if it introduced any unintended consequences.

**Comment by craftzdog** [comment]
Cool, Thanks!

**Comment by craftzdog** [comment]
v1.2.0 has been released, closing it
