### ISSUE TITLE
Client doesn't update/save new notes after a few are created

### ISSUE THREAD

**Issue by mohrbius** [inkdropapp/forum#35]
## Bug report
Mass creating new notes (1 at a time), whether in nested notebook folders or not, stops working after a few notes are created.  The client will act as if it didn't save the new note.  Clicking back on EXISTING notes doesn't cause the client to update its window w/ the contents of the existing note, either - it's as if the client itself freezes up.  You can click on notebooks and notes but the screen doesn't change.  Tested the latest Mac and Windows versions of Inkdrop and it appears to only happen on Mac.

### Info
- Platform: macOS
- Platform version: Sierra 10.12.3
- App Version: (3.3.0 for Mac)

### Reproduce
1. Reproducing with "Inkdrop Sync Server" Sync option selected
2. Create new note - type in TITLE and PASTE in contents of note from another notetaking app.
3. Repeat step #2 a few more times.
4. Eventually, the note's TITLE column will STAY at "Untitled" (which is default when creating a new note) and the contents of the note will be blank.
5. Click on another EXISTING note and both it's TITLE column as well as the actual NOTE pane for the note doesn't update from the bugged on.

Very frustrating.

**Comment by mohrbius** [comment]
UPDATE:
Seems 100% related to sync.

If I disable sync and choose to store locally, I have been chewing through LOADS of new notes and haven't had it give me a problem.

**Comment by mohrbius** [comment]
Ok maybe not 100% related, still encountered it but it took WAY longer to present itself.

**Comment by craftzdog** [comment]
Hi, thank you for the report!

It seems to be critical and it must be fixed.
I tried to reproduce the problem, but I couldn't.
There may be errors occurring. Could you check console by using  *Developer -> Toggle Developer Tools* menu?
After restarting the app, does the problem still persist?

**Comment by craftzdog** [comment]
I got an error which occurred when preview pane is shown:

![screen shot 2017-04-04 at 14 32 56](https://cloud.githubusercontent.com/assets/1332805/24642641/af623514-1943-11e7-81b4-2a198e5da8a8.png)

It causes a failure of opening notes.
I guess it is related to this issue and is introduced in v3.3.0.
I'm gonna fix it as soon as possible!

**Comment by craftzdog** [comment]
It can be reproduced after selecting multiple notes once, then the editor stops working.

**Comment by craftzdog** [comment]
Could you try v3.3.1 just released now?
You can close it if it's resolved.

**Comment by mohrbius** [comment]
You may have fixed it with your 3.3.1, now - nice job!
I've gone through all of my "New Note" creation steps and the problem didn't follow with the new iteration.

**Comment by craftzdog** [comment]
Great! Thanks for reporting :D
