### ISSUE TITLE
Horizontal line interacting with next line bullet feature

### ISSUE THREAD

**Issue by ghacct22** [inkdropapp/forum#38]
## Bug report
When you add a horizontal line either manually, with the button, or with the cmd+shift+H hotkey, the cursor goes to the end of the `* * *`, and generally people press `enter` to go to the next line. This does not happen and instead extra asterisks are created in following with the bulleted list auto-set-next-line-as-list-item feature. Maybe this is intended functionality, but i don't think so.

### Info
- Platform: macOS
- Platform version: Sierra
- App Version: 3.3.4

### Reproduce
1. Edit text in the edit panel
2. add a horizontal line with the button or `cmd+shift+H`
3. press the `enter` key

### Expected Outcome
The cursor goes to the next line without any inserted characters, and typing continues as normal

### Actual Outcome
The cursor goes to the next line, and `*` is inserted at the start of the line, like when you go to the next line when writing a bulleted list.

**Comment by craftzdog** [comment]
Thank you for the report!
Just as you said, it's due to the continuous list feature and it should be suppressed for lines of `* * *`.
I'll fix it.

**Comment by craftzdog** [comment]
Fixed in v3.4.0. Thanks!
