### ISSUE TITLE
Encrypt whole notebooks

### ISSUE THREAD

**Issue by josefdlange** [inkdropapp/forum#4]
I'd think this might be possible. Maybe even just cheating; an "encrypted" notebook just means that all of its notes get encrypted and share the same password. 

Setting a password on a notebook would put its salt/hash in the notebook data structure (however you've organized it), and then the client app would be able to verify the password is the right password, then keep it in memory to decrypt any notes belonging to that notebook, having made the assumption that all notes belonging to that notebook are encrypted with that validated password.

Changing a notebook encryption password would be a pain in the ass (essentially needing old password to decrypt all notes and new password to re-encrypt all the notes) but it'd be possible I'd think.

**Comment by craftzdog** [comment]
Indeed securing notes is important and it's not impossible theoretically but there is sec/cost/perf constraints.
One of the performance issue is that full-text search will significantly lost its performance. Listing notes are also slowed down. So it may need to decrypt all notes once at every app launch and it will take long time.
Changing a notebook encryption password would also cause the potential to corrupt note data and be difficult to keep syncing.

I'd like to hear any idea about this security related topic. Thanks.

**Comment by craftzdog** [comment]
I came up with an idea to encrypt all notes.
Each notes will be encrypted transparently when synced to remote database with a common key.
Notes are stored after its decryption in local so the performance is not affected.
The common key is also encrypted with login password so the full re-encryption is not necessary when changed the password. Therefore all notes are yet secure if remote database was compromised.

Although this is not perfect solution compared with encrypting whole data, it's applicable solution and retains extensibility of the app.

**Comment by craftzdog** [comment]
Note that the data will be lost if users forgot their password in this approach.

**Comment by craftzdog** [comment]
Data at rest encryption is now supported and the note encryption with password is deprecated.
Read a blog post for detail info: https://medium.com/@inkdrop/inkdrop-v0-11-0-is-out-b708a9c2cd49
