### ISSUE TITLE
Checkbox formatting includes bullets

### ISSUE THREAD

**Issue by ghacct22** [inkdropapp/forum#40]
## Bug report
I've found that adding checkboxes not only aren't ever clickable, but they have a bullet next to them and you can't have them without the bullet (that i've found)

### Info
- Platform: macOS
- Platform version: Sierra
- App Version: 3.3.4

### Reproduce
Make a checkbox in markdown `* [ ]`

### Expected Results
In preview mode, a checkbox is shown

### Actual Results
In preview mode, a bullet and then a checkbox is shown

**Comment by craftzdog** [comment]
Hi,

You are right, bullets should be not shown in the task list.
It's a problem of the Markdown renderer library called [remark](https://github.com/wooorm/remark) but I guess it's resolved in the recent version of it.
I'm planning to upgrade it.
It includes breaking changes, so it may take a while.
Please wait until then!

Thanks!

**Comment by craftzdog** [comment]
This should be fixed in v3.4.0.
