### ISSUE TITLE
Hide Menu Bar on Windows

### ISSUE THREAD

**Issue by livejamie** [inkdropapp/forum#41]
It would be nice to have an option to hide or toggle the menu bar at the top. 

Most apps do this by pressing Alt.

**Comment by craftzdog** [comment]
Hi, thanks for the suggestion!

Pressing alt key sets focus to the menu on the most Windows apps like Explorer by default.
I could support auto hide menu bar but it makes difficult to find where it is for newbies.

Instead of supporting it by the app itself, it'd be nice to make a plugin for it.

**Comment by craftzdog** [comment]
It can be easily supported with `autoHideMenuBar` of Electron API:
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

**Comment by marvolo3d** [comment]
Any hope of a plugin for this? I'm trying to create one but failing as I don't know anything about electron programming.

**Comment by craftzdog** [comment]
Yeah, I see many upvotes here. Seems like it's important!
I will work on it anytime soon.

**Comment by craftzdog** [comment]
`hide-menu-bar` plugin is now available:
https://app.inkdrop.info/plugins/hide-menu-bar
