### ISSUE TITLE
Spell check in edit mode

### ISSUE THREAD

**Issue by ghacct22** [inkdropapp/forum#42]
## Feature Request
It would be nice to have a spell checker in edit mode. I hadn't realized how dependent i've become on it until it wasn't available.

**Comment by craftzdog** [comment]
Hi, thanks for the feature request!

I think it's a language-specific feature so it's good to be a plugin.
I guess that the spell checker should be turned off in the code blocks.

Just an implementation memo: http://stackoverflow.com/questions/12343922/codemirror-with-spell-checker

**Comment by sethfox** [comment]
+1 for this request

Any thoughts on when this may be added?

**Comment by craftzdog** [comment]
Not planned unfortunately as its priority is low for now.
Here is the roadmap: https://blog.inkdrop.info/the-future-work-of-inkdrop-8c50c4e06e6c
After finishing current roadmap, other feature requests would be considered again.
Thanks for the upvote.

**Comment by sethfox** [comment]
understood that for the update. Kind of a base line need for my use case tho. The quest for a markdown editor continues!

**Comment by craftzdog** [comment]
This topic has been moved to the new forum: https://forum.inkdrop.info/t/spell-check-in-edit-mode/55

**Comment by craftzdog** [comment]
Spell checker plugin is finally available: https://app.inkdrop.info/plugins/spell-checker
