### ISSUE TITLE
Why are the Status tags handled differently than other tags?

### ISSUE THREAD

**Issue by ghacct22** [inkdropapp/forum#43]
This isn't really a feature or a bug, just wondering why the Status options for notes are handled differently than other tags. Aren't they essentially the same thing? I mean, status tags have special icons, and default views exclude ones like 'completed' which is great, but it just seems like a separate tagging system when one already exists.

**Comment by craftzdog** [comment]
Tag can coexist but status must be one.
I mean, if the status is tag, you may add `completed` and `dropped` and they conflict.
So it can't be the tagging system.
