### ISSUE TITLE
Request: Dark UI also available for iOS app

### ISSUE THREAD

**Issue by fmaida** [inkdropapp/forum#44]
Hello,

I own both a Mac and an iPhone and I love dark interfaces. I like the dark UI you've made available on Mac, and I'd like to use the very same UI under iOS; actually I can set the syntax theme to dark mode, but AFAIK I can't set dark UI.

Are you planning to add this feature on a future update of your iOS app?

Many thanks

**Comment by craftzdog** [comment]
Hi,

Thanks for the request!
Yes, the dark UI is planned to support after releasing the Android app.
Please look forward to it!

**Comment by fmaida** [comment]
Thank you
