### ISSUE TITLE
Ability to duplicate/clone existing notes

### ISSUE THREAD

**Issue by geoffwellman** [inkdropapp/forum#46]
Currently, I have to copy and paste several notes that I use as templates where the structure is going to be the same. 

It would be good if I could easily duplicate these via the right click menu or some equally easy method.

**Comment by craftzdog** [comment]
okay. thanks for the suggestion!

**Comment by craftzdog** [comment]
Supported in v3.5.0. Thanks!

**Comment by geoffwellman** [comment]
Thank you! This is awesome.
