### ISSUE TITLE
Images cannot be viewed on Android app

### ISSUE THREAD

**Issue by kelchm** [inkdropapp/forum#48]
![screenshot_20170628-150659](https://user-images.githubusercontent.com/172301/27655499-9c9d2b06-5c13-11e7-872c-603f12209f98.png)

**Comment by craftzdog** [comment]
Hi, thanks for the report.

Could you check if the image URI is not broken?
If the problem persists, please tell me your device type and OS version.

**Comment by kelchm** [comment]
@craftzdog,

I added the image to my note by dragging and dropping it on the editor windows (so it was created as an internal inkdrop link. 

Example:
```
![foo.png](inkdrop://file:rJz4sx74-)
```

**Comment by craftzdog** [comment]
Related to #50

**Comment by craftzdog** [comment]
Please reopen the issue if the problem still persists.
