### ISSUE TITLE
Improve Look and Feel of Android App

### ISSUE THREAD

**Issue by kelchm** [inkdropapp/forum#49]
The Android app, while functional, doesn't really look or feel like an Android app. I'd suggest Google Inbox as a 'similar' app that might be a good example of the Material Design guidelines.

Some of the things that come to mind for me:
- Allow opening the hamburger menu with a swipe from the left edge of the screen
- Use the [Floating Action Button](https://material.io/guidelines/components/buttons-floating-action-button.html) for creating new notes.
- The bar bellow the toolbar should be eliminated. Search should be a top level item on the toolbar, sync, sort and settings can hidden under an overflow menu.
- Use a 'pull to refresh' gesture
- Default to 'preview' rather than edit mode when viewing notes

**Comment by craftzdog** [comment]
Yeah it should be better to follow Material Design.
It's helpful because I'm a long time iOS user :)
I will keep them in mind for the future releases!
Thank you for the suggestion.

**Comment by Tinamattew** [comment]
Thanks for the suggestion. I am gadget freak and loves to buy android phones. I also like to learn about apps and gadgets from android authority, TechCrunch and a new blog TechRubik http://techrubik.com
