### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by josefdlange** [inkdropapp/forum#5]
D'you think it'd be possible to enable text wrapping in the editor? Not necessarily by default, but as a setting in-app.

**Comment by craftzdog** [comment]
The line wrapping is enabled by default.
Is it not enabled?
Sure to make it switchable from preferences.

**Comment by angstwad** [comment]
Wrapping is enabled in the preview, but not in the editor.  It'd be useful!

**Comment by craftzdog** [comment]
It's a same bug as #9. going to be fixed in next version. :)
