### ISSUE TITLE
Inkdrop will not sync

### ISSUE THREAD

**Issue by kelchm** [inkdropapp/forum#50]
## Bug report
```
/Applications/Inkdrop.app/Contents/Resources/electron.asar/renderer/api/remote.js:284 Uncaught (in promise) Error: missing
    at /Applications/Inkdrop.app/Contents/Resources/electron.asar/renderer/api/remote.js:284:16
    at metaToPlainObject (/Applications/Inkdrop.app/Contents/Resources/electron.asar/renderer/api/remote.js:288:5)
    at metaToValue (/Applications/Inkdrop.app/Contents/Resources/electron.asar/renderer/api/remote.js:230:14)
    at metaToValue (/Applications/Inkdrop.app/Contents/Resources/electron.asar/renderer/api/remote.js:222:22)
    at EventEmitter.<anonymous> (/Applications/Inkdrop.app/Contents/Resources/electron.asar/renderer/api/remote.js:299:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Info
- Platform: macOS 10.12.4 / Windows 10
- App Version: 3.6.0

### Reproduce
After logging in to Inkdrop on either of my systems I see 'Syncing...' flash in the bottom left continuously, but my notes never sync.

**Comment by craftzdog** [comment]
Hi.

Inkdrop server is working.
I guess you might update your notes too often because Inkdrop has rate limit.
Please wait for an hour and try again.

**Comment by kelchm** [comment]
For that it's worth, I only had one or two notes created and just started using the application yesterday.

**Comment by craftzdog** [comment]
When did it start getting stuck in syncing?
Please tell me what you did if you have any idea.

**Comment by craftzdog** [comment]
You changed password and that caused this problem. Sorry!
I'm working on fixing it.
Thank you for the report.

**Comment by craftzdog** [comment]
fixed it.
Could you try it again?

**Comment by kelchm** [comment]
That seems to have improved things, but even after logging out / logging back in my Windows 10 system seems to be unable to pull down any existing notes. Newly created notes/folders on that system _do_ sync to my other devices.

**Comment by craftzdog** [comment]
How many notes can you see?
I confirmed that 10 notes are stored in the server and 9 of them have been moved to the trash.
I assume that your account is k***m@g***.com, just in case.

**Comment by craftzdog** [comment]
Please reopen the issue if the problem still persists.
