### ISSUE TITLE
Closing search box with esc on mac closes the full screen mode

### ISSUE THREAD

**Issue by iskeld** [inkdropapp/forum#53]
## Bug report
Cannot close current-note search with ESC key without closing the full screen mode on mac.

### Info
- Platform: macOS
- Platform version: 10.12.5
- App Version: 3.6.1

### Reproduce
1. Toggle full screen.
2. Press Cmd+F to start current-note search.
3. Press esc to close the search.
Search is closed but so is full screen :(

**Comment by craftzdog** [comment]
Thank you for the report!
I would remove the behavior of 'ESC key to exit fullscreen'.

**Comment by iskeld** [comment]
Thank you for the reply :). Just one remark - since many apps share this behavior (ESC closing full screen) maybe it would be possible for ESC to act both ways - depending on the focus. 
1. If the focus is in the search field then ESC closes the search field
2. Otherwise, it exits the fullscreen

For instance, in my browser while having the cursor inside this comment field, pressing esc causes the field to lose focus. If the text cursor is not in the field (no focus) then ESC exits the fullscreen.

I think such behavior would be the best :)

**Comment by craftzdog** [comment]
Sure, it's easy.
I was just trying to follow Safari's behavior but I think you are right.
Thanks!

**Comment by craftzdog** [comment]
Resolved in v3.7.0.
Thanks again for the report!
