### ISSUE TITLE
Render MD tables in preview

### ISSUE THREAD

**Issue by flyinggrizzly** [inkdropapp/forum#55]
## Feature request
As as user
I want Markdown tables to render as tables in preview
So I can present information in an appropriate way.

### Info
A table row `| td | td | td |` or `td | td | td` should render out a table, per MD spec.

**Comment by craftzdog** [comment]
Hi, thanks for the request.

You can write tables as following code:

```markdown
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

Please read [this documentation](https://doc.inkdrop.info/manual/markdown-cheatsheet#tables) for more information.
Hope it helps!
