### ISSUE TITLE
Prevent clearing search keywords of in-note-search on `editor:find`

### ISSUE THREAD

**Issue by wapa5pow** [inkdropapp/forum#58]
## Bug report

<img width="954" alt="inkdrop_ _releases-3_7_0" src="https://user-images.githubusercontent.com/5561944/28106345-815b5d7a-671e-11e7-90ab-5fd675f9637b.png">

I think it's better to keep search text remains. However, if the text remains it's tedious to delete it when user want to use other text. To mitigate the situation, I suggest select all search text after cmd-f like the following. In that case, an user can delete or replace the search text easily.

<img width="172" alt="inkdrop" src="https://user-images.githubusercontent.com/5561944/28106441-ca329784-671e-11e7-9443-dd0513e32236.png">

### Info
- Platform: (macOS)
- Platform version: (Sierra 10.12.5)
- App Version: (3.7.1)

**Comment by craftzdog** [comment]
Thank you for the report.
Yeah it seems like the search keyword has to be restored depending on the editor's search state.
Will be fixed!

**Comment by craftzdog** [comment]
Resolved in v3.7.2.
Thanks again!

**Comment by wapa5pow** [comment]
Thx!!! It's great improvement. Now, I move from Dash to Inkdrop. Great work. I really appreciate it.
