### ISSUE TITLE
Roll-your-own-backend, or local backend

### ISSUE THREAD

**Issue by josefdlange** [inkdropapp/forum#6]
It'd be nice to be able to roll my own back-end, or even just keep the DB local.

**Comment by craftzdog** [comment]
I need more consideration for that in Inkdrop roadmap. Thanks for your suggestion.

**Comment by MauledByLove** [comment]
Yes, please. Without a way to at least disable sync, the app is unusable in many corporate environments.

**Comment by craftzdog** [comment]
Local only mode and custom database are supported now.
Read the documentation for more info: http://doc.inkdrop.info/manual/synchronizing-in-the-cloud
