### ISSUE TITLE
Securing data

### ISSUE THREAD

**Issue by wapa5pow** [inkdropapp/forum#60]
## Question

Right now, I am using Dash snippet storing data in dropbox so that I can store kinda secret information only in dropbox. I understand your cloud should be safe but I want to minimize the risk.

Other than using own CouchDB, is there any other option to use dropbox or so as storage?
(If not, I can manage to create my own CouchDB so I'm just asking the question.)

***If it is not suitable to ask question here, please let me know.***

### Info
- Platform: (macOS)
- Platform version: (Sierra 10.12.5)
- App Version: (3.7.2)

**Comment by craftzdog** [comment]
Inkdrop won't support the file based sync such as Dropbox.
You can disable the sync.
Please refer to the documentations for more information: https://doc.inkdrop.info/faq and https://doc.inkdrop.info/security
Hope it helps.
