### ISSUE TITLE
Doesn't save, can't delete either

### ISSUE THREAD

**Issue by timsuchanek** [inkdropapp/forum#62]
## Bug report
Write the description of the issue here.
If you got a problem, please check if you got any error in the console log by selecting the menu: `Developer -> Toggle Developer Tools`.

![image](https://user-images.githubusercontent.com/1094804/28365164-bb42c1cc-6c87-11e7-8ae9-e731ee230c11.png)

### Info
- Platform: macOS
- Platform version: Sierra 10.12
- App Version: 3.7.1

### Reproduce
Delete doesn't work anymore, also no notes are saved. Makes the app pretty much useless at the moment

**Comment by craftzdog** [comment]
Hi,

Thank you for reporting and sorry for the inconvenience.
Seems like it's working on my environment.
Does it occur only on particular note?

**Comment by timsuchanek** [comment]
I think I know what the problem is: A few days ago I hit the space limit of my harddrive - all other apps worked since then. But inkdrop couldn't save since then. A reboot fixed it.

**Comment by craftzdog** [comment]
Thank you for the information.
Good to hear that your database wasn't broken!
It makes sense because Inkdrop saves notes in local disk.
Please let me know if you have any other problem.
Closing it.
