### ISSUE TITLE
Showing "&nbsp" in Preferences panel

### ISSUE THREAD

**Issue by S1ngS1ng** [inkdropapp/forum#65]
## Bug report
There is a `&nbsp` showing in the header.

### Info
- Platform: macOS
- Platform version: Sierra
- App Version: 3.7.2

### Reproduce
- Open the `Preference` panel and click on `Plugins`

### Screenshot
![image](https://user-images.githubusercontent.com/13592559/29202637-1a34a1f2-7e38-11e7-86a9-7f1f040264f2.png)

**Comment by craftzdog** [comment]
Oops 😅  thank you for the report!
It will be fixed in the next version.

**Comment by craftzdog** [comment]
Fixed in v3.7.3. Thanks again!
