### ISSUE TITLE
GraphQL Syntax Highlighting

### ISSUE THREAD

**Issue by timsuchanek** [inkdropapp/forum#66]
I'm using Inkdrop a lot for saving code snippets locally.
As I'm working with GraphQL everyday, having syntax highlighting for
``````
```graphql
query {
  allItems(first: 10) {
    id
    title
  }
}
```
``````

```graphql
query {
  allItems(first: 10) {
    id
    title
  }
}
```

would be really awesome.
Thanks!

**Comment by craftzdog** [comment]
Hi, thanks for the request!
Yeah, that would be nice.
I found [codemirror-graphql](https://github.com/graphql/codemirror-graphql), so it seems to be possible to support ;)

**Comment by craftzdog** [comment]
![screen shot 2017-08-11 at 20 42 22](https://user-images.githubusercontent.com/1332805/29211709-97e6dca8-7ed5-11e7-812d-ba0066e9673e.png)

It works well. Will release it in the next version.

**Comment by craftzdog** [comment]
Supported in v3.7.3.

**Comment by timsuchanek** [comment]
Awesome!! Thanks for building this in!
![image](https://user-images.githubusercontent.com/1094804/29252945-5abb7b16-8071-11e7-8f76-69fda0eeaa8f.png)

**Comment by craftzdog** [comment]
I'm happy to hear that 😆
