### ISSUE TITLE
Missing wrench-js for npm install

### ISSUE THREAD

**Issue by marvolo3d** [inkdropapp/forum#67]
I'm following the UI themeing guide, and it seems the derekslife wrench-js repo is gone.

Output of `npm install`:

```
npm ERR! fetch failed https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm ERR! fetch failed https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

Any suggestions?

**Comment by craftzdog** [comment]
Seems like it works well without wrench-js.
Just updated `package.json` of the [inkdrop-ui-theme-template](https://github.com/inkdropapp/inkdrop-ui-theme-template).
Could you try it again?

**Comment by marvolo3d** [comment]
Yes, that helps. Thanks

**Comment by craftzdog** [comment]
Good to hear that 😄
Looking forward to seeing your theme!
