### ISSUE TITLE
C# Syntax Highlighting Uses Different Keywords in Edit vs Preview

### ISSUE THREAD

**Issue by timothy-s-dev** [inkdropapp/forum#68]
## Bug report
With the default themes, syntax highlighting for C# can be used in the editor using either: 
```
```c#
```
or
```
```csharp
```

But neither of these turn on syntax highlighting in the preview.  Conversely, if you use:
```
```cs
```

You get syntax highlighting in the preview, but not the editor.

![image](https://user-images.githubusercontent.com/1112527/29319175-0ef7c924-81a1-11e7-83b5-1fe37bec2bb4.png)

### Info
- Platform: Windows
- Platform version: 10
- App Version: 3.7.3

**Comment by craftzdog** [comment]
Hi, thank you for reporting it!
This is due to what name of the language is registered in `highlight.js` and `CodeMirror`.
I think `c#` is appropriate.
I will fix it!

**Comment by timothy-s-dev** [comment]
Looks like there may be a similar case with `basic` vs `vb`

**Comment by craftzdog** [comment]
Thanks! Will be fixed

**Comment by craftzdog** [comment]
Fixed in v3.8.0. Thanks again!

**Comment by timothy-s-dev** [comment]
Awesome, thank you!
