### ISSUE TITLE
Encrypted note (feature request)

### ISSUE THREAD

**Issue by chuckg** [inkdropapp/forum#71]
Although data is encrypted on the server, it would be a nice feature to add an "encrypted note" feature for local storage as well.  

- These notes would encrypt everything except the title/tags of the note (to allow for searching)
- The body of the message would be garbled unless a password is supplied
- Each note can be encrypted with a unique password
- Remotely these messages would be stored garbled and only decrypted locally with the password

In particular this area is interesting for documenting / archiving highly sensitive information like Social Security Number in the US, notes you don't want someone opening while your computer is unlocked, or notes you don't want indexed by any search facilities built into your OS.

**Comment by craftzdog** [comment]
Hi,

Thank you for the suggestion.
I understand your need for storing highly sensitive information in notes.
It would come in handy if all informations you use daily were stored in one place.
But I recommend you to use 1Password which I use or similar apps out there for storing such sensitive things.
I'm afraid that Inkdrop would keep to be simple and would not like to have such complicated features which would be not so often used and may cause significant bugs.
This is just a Markdown note-taking app for daily hacking but not for archiving sensitive informations.
Thanks again for considering the use-case.

Best regards
