### ISSUE TITLE
Characters are not overwritten even if pasted while selecting the characters

### ISSUE THREAD

**Issue by obiyuta** [inkdropapp/forum#74]
## Bug report

Copy characters and pasting it while selecting characters.
the selecting characters should be overwritten with the pasted characters.
However, the pasted characters are append to the end of the selecting characters.

![kapture 2017-08-30 at 11 02 12](https://user-images.githubusercontent.com/3177114/29852051-c5f6ced6-8d72-11e7-940a-28acc354b5e9.gif)

### Info
- Platform: (macOS)
- Platform version: (Sierra/10/12.05)
- App Version: (3.10.1)

### Reproduce

- Copy some characters.
- Paste it  while selecting characters.
- It will be appended to the end of the selecting
- (the selecting should be overwritten)

**Comment by craftzdog** [comment]
Thanks!
I'm aware of this and I'm just about to fix it. Hold on.

**Comment by craftzdog** [comment]
This was due to supporting the pasting HTML as Markdown feature recently introduced.

**Comment by obiyuta** [comment]
Thanks for fixing!
I guessed this was due to the feature too.

頑張ってください！🍣

**Comment by craftzdog** [comment]
should work correctly in v3.10.2!
Thanks for 🍣
