### ISSUE TITLE
Doesn't work left arrow button in Status screen of Android app

### ISSUE THREAD

**Issue by aoshimanoa** [inkdropapp/forum#75]
Hello.
Thank you for serve such a wonderful app.
I found a trivial bug. Please fix it in your spare time.

## Bug report
In "Status" screen, left arrow don't work in Android App.

### Info
- Platform: Android
- Platform version: Android7.0 ( FTJ162E )
- App Version: 1.3.1

### Reproduce
1. touch the humberger menu 
2. touch the "Status" from the list
3. In "Status" screen, touch the left arrow, it seems go back previous menu but it doesn't work.

**Comment by craftzdog** [comment]
Hi, thank you for the report!
I confirmed the back button on switching status screen doesn't work.
Will fix it!

**Comment by craftzdog** [comment]
Fixed in v1.3.2.
Thanks for the report!
