### ISSUE TITLE
Freeze on splash screen after re-launch

### ISSUE THREAD

**Issue by opack** [inkdropapp/forum#77]
## Bug report
When exiting the app and trying to launch it again, it freezes on the splash screen.
The only way to get the app running correctly again is to kill it and then launch it again.

### Info
- Platform: Android
- Platform version: 5.0 (LRX21V.N9005XXSGBPL6
- App Version: 1.3.1

### Reproduce
1. Launch the app
2. Tap on the "Back" key to exit the app
3. Try to launch the app again : it stays on the Inkdrop welcoming flash screen.

**Comment by craftzdog** [comment]
Hi,

Thank you for the report!
It is known issue and I'm planning to focus on improving the mobile version and it is going to be fixed!

**Comment by opack** [comment]
Ok fine ! :-)

First, thanks for the quick reply. Second, thanks a lot for this great app. I am in the process of comparing the various note taking solutions using markdown, and Inkdrop is currently #1 in my top 3. However, as I take a lot of notes on mobile, in my case if the app is not functional it is a big issue.
**Do you have an estimate on a fix ? Not a precise date, but are we talking about days, weeks, months, years ?**

Thanks in advance, and once again : great great job :-)

**Comment by craftzdog** [comment]
I'm so happy to hear that!

Actually this freezing problem is not the issue regarding performance.
It's just a navigation problem where the app won't receive the event for moving on to the next screen and it isn't freezing.

I have over 700 notes already stored in the app but I don't see any big performance issue for now.
Of course, I would really care about it.
It should be made for long-term use, and should work even with tons of notes.

Thanks again for your thought!

**Comment by opack** [comment]
Sorry but you did not provide an answer to my main interrogation ^^ Do you have an estimate on a fix ? Not a precise date, but are we talking about days, weeks, months, years ?

Or maybe there is some known workaround (other that killing-relaunching) ?

**Comment by craftzdog** [comment]
Oops, sorry.
I would answer that it will be fixed in this year!
It's not so difficult problem but it depends on the priorities of tasks.
So it could be fixed soon if other tasks are finished earlier.

**Comment by opack** [comment]
Thanks a lot for the clear answer, and a last time, really great job for this app :-)

**Comment by craftzdog** [comment]
Fixed in v1.3.2.
I decided to fix it first because it seems to be very inconvenience for users.
Thanks for the report!

**Comment by opack** [comment]
Waouw ! Already ! 😊
Great ! I tested and it is fixes.
Thanks a lot for your quick answers and fix !

**Comment by craftzdog** [comment]
You're welcome :)
Would you mind upvoting Inkdrop on this software comparison website?
https://alternativeto.net/software/inkdrop/
Thanks again!

**Comment by opack** [comment]
Done ;-)

**Comment by craftzdog** [comment]
Thank you❤️
