### ISSUE TITLE
Window resize in side-by-side view mode resets scroll position

### ISSUE THREAD

**Issue by greysond** [inkdropapp/forum#8]
If you resize the window while editing in Side-by-Side mode, the scroll position is reset, which is pretty annoying.

This is on OS X, with Inkdrop version 0.2.4

**Comment by GreysonD** [comment]
I should note, this is on OS X, with Inkdrop version 0.2.4.

**Comment by craftzdog** [comment]
Thanks for reporting! I'm gonna look into this issue.

**Comment by craftzdog** [comment]
Resolved in v0.6.2.
Thanks again!
