### ISSUE TITLE
Horizontal spacing at end of the line in editor is too slim

### ISSUE THREAD

**Issue by hackersoup** [inkdropapp/forum#9]
When typing a single line long enough to cause a horizontal scroll, the cursor is placed exactly at or beyond the far right edge of the screen, causing it to not appear, or to obstruct part of the last letter. 

Steps to reproduce: Enter the sentence below and notice the behavior of the cursor at the end of the line.
This is a really long and rambling sentence to demonstrate the existence of a bug in this wonderful application

Using version 0.3.0 on Mac 10.11.5

**Comment by craftzdog** [comment]
Hi, thanks for reporting.
Could you put a screenshot?
The long line should be wrapped by default but it's sometimes not working.
I'm looking into it.

**Comment by hackersoup** [comment]
Sentence wrapping works properly when that line is pasted into the editor. When the line is typed by hand, the line does not wrap and is at the very edge of the window. The following screenshot was taken after typing a sentence longer than the screen allows.

<img width="1079" alt="screen shot 2016-06-21 at 12 00 52 pm" src="https://cloud.githubusercontent.com/assets/9868309/16238883/ea04390c-37a7-11e6-931a-34c0125a6ac8.png">

Additionally, it seems when there are enough lines to cause the vertical scroll bar to appear, the offset is not adjusted for this as the scroll bar overlaps text as well. This screenshot uses the same sentence as above, but with enough blank lines under to cause the vertical scroll bar to appear:

<img width="1080" alt="screen shot 2016-06-21 at 12 00 36 pm" src="https://cloud.githubusercontent.com/assets/9868309/16238862/d8ccf99e-37a7-11e6-8f60-b772908abd49.png">

**Comment by craftzdog** [comment]
Got it, I could reproduce that.
It only occurs when an empty note is opened after showing other note in preview mode.
That will be fixed in next version.
Thank you for your detail report!🙌

**Comment by craftzdog** [comment]
please ⌘+R to reload to avoid this bug when happened for now.

**Comment by craftzdog** [comment]
resolved in v0.4.0
